# 공공데이터를 이용한 카페 상권분석(2020)

- 공공데이터포털(data.go.kr)에 다양한 데이터가 공개되어있다.

### 명세사항
- 1. 전국 카페 데이터를 모두 수집해야한다.
- 2. 지역별 or 브랜드별 점포현황을 확인한다.
- 3. 분석결과를 시각화한다.

[데이터](https://www.data.go.kr/data/15083033/fileData.do)

In [1]:
import pandas as pd

## 1. 데이터 불러오기

In [5]:
temp = pd.read_csv("data/소상공인시장진흥공단_상가(상권)정보_광주_202103.csv", encoding='utf=8')
temp

C:\Users\user\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (35) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,23422020,달빙고,선운점,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,2920010700106540000000001,NaN,광주광역시 광산구 선운로20번길 38,506100,62402.0,NaN,1,NaN,126.774758,35.146865
1,25195570,그남자의지름신,NaN,D,소매,D05,의복의류,D05A01,일반의류,G47416,...,2915511500110110008005503,조치과,광주광역시 남구 봉선1로 46-1,503060,61695.0,1,NaN,NaN,126.910337,35.127716
2,23249359,휴먼세탁소,NaN,F,생활서비스,F02,세탁/가사서비스,F02A01,세탁소/빨래방,S96912,...,2915510700102190000000001,송화마을휴먼시아5단지아파트,광주광역시 남구 노대실로 33,503875,61746.0,NaN,NaN,103,126.907947,35.106187
3,25217643,에이치에스이허석영어,NaN,R,학문/교육,R04,학원-어학,R04A01,학원-외국어/어학,P85502,...,2911010800101510003009898,NaN,광주광역시 동구 장동로 23-12,501813,61436.0,NaN,3,NaN,126.924898,35.148461
4,20739262,오프라인컴퓨터,NaN,F,생활서비스,F03,개인/가정용품수리,F03A07,컴퓨터수리,S95121,...,2914011500106500324002313,NaN,광주광역시 서구 화운로304번길 15-1,502802,61913.0,NaN,1,NaN,126.879169,35.165921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68991,17456374,벨루가,NaN,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,2920011400114430000000001,NaN,광주광역시 광산구 임방울대로332번길 25,506304,62306.0,NaN,3,301,126.825281,35.189748
68992,17456214,피커피,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,2911010800102000169006031,NaN,광주광역시 동구 동명로 19,501815,61430.0,NaN,1,NaN,126.923241,35.150961
68993,17433009,평동한식당,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,2920014600112370000000001,NaN,광주광역시 광산구 평동산단로 170-3,506501,62418.0,B,1,NaN,126.768948,35.122441
68994,17451393,썬,NaN,F,생활서비스,F02,세탁/가사서비스,F02A05,청소/소독,NaN,...,2920010900115870001045107,콜럼버스월드,광주광역시 광산구 풍영철길로 15,506813,62355.0,NaN,1,118-1,126.811684,35.162889
68995,17433218,페르메,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,2920011500108850001043985,월계동주차빌딩,광주광역시 광산구 첨단중앙로106번길 65-3,506824,62277.0,NaN,1,122,126.846399,35.215135

In [6]:
data = temp[['상호명', '지점명', '상권업종대분류명','상권업종중분류명','시도명','시군구명','행정동명']]
data

              상호명  지점명 상권업종대분류명   상권업종중분류명    시도명 시군구명  행정동명
0             달빙고  선운점       음식         분식  광주광역시  광산구   어룡동
1         그남자의지름신  NaN       소매       의복의류  광주광역시   남구  봉선1동
2           휴먼세탁소  NaN    생활서비스   세탁/가사서비스  광주광역시   남구   효덕동
3      에이치에스이허석영어  NaN    학문/교육      학원-어학  광주광역시   동구   동명동
4         오프라인컴퓨터  NaN    생활서비스  개인/가정용품수리  광주광역시   서구   광천동
...           ...  ...      ...        ...    ...  ...   ...
68991         벨루가  NaN       음식       유흥주점  광주광역시  광산구   수완동
68992         피커피  NaN       음식         한식  광주광역시   동구   동명동
68993       평동한식당  NaN       음식         한식  광주광역시  광산구    평동
68994           썬  NaN    생활서비스   세탁/가사서비스  광주광역시  광산구   우산동
68995         페르메  NaN       음식         한식  광주광역시  광산구  첨단2동

[68996 rows x 7 columns]

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68996 entries, 0 to 68995
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   상호명       68996 non-null  object
 1   지점명       10152 non-null  object
 2   상권업종대분류명  68996 non-null  object
 3   상권업종중분류명  68996 non-null  object
 4   시도명       68996 non-null  object
 5   시군구명      68996 non-null  object
 6   행정동명      68996 non-null  object
dtypes: object(7)
memory usage: 3.7+ MB

In [8]:
del temp

In [ ]:
temp.head() # 삭제함 그래서 오류가 남..

In [9]:
set(data["상권업종대분류명"])

{'관광/여가/오락', '부동산', '생활서비스', '소매', '숙박', '스포츠', '음식', '학문/교육'}

In [10]:
set(data["상권업종중분류명"])

{'PC/오락/당구/볼링등',
 '가구소매',
 '가방/신발/액세서리',
 '가전제품소매',
 '가정/주방/인테리어',
 '개인/가정용품수리',
 '개인서비스',
 '건강/미용식품',
 '경마/경륜/성인오락',
 '광고/인쇄',
 '기타서비스업',
 '기타음식업',
 '기타판매업',
 '놀이/여가/취미',
 '닭/오리요리',
 '대중목욕탕/휴게',
 '대행업',
 '도서관/독서실',
 '모텔/여관/여인숙',
 '무도/유흥/가무',
 '물품기기대여',
 '민박/하숙',
 '법무세무회계',
 '별식/퓨전요리',
 '부동산임대',
 '부동산중개',
 '부페',
 '분식',
 '분양',
 '사무/문구/컴퓨터',
 '사진',
 '사진/광학/정밀기기소매',
 '선물/팬시/기념품',
 '세탁/가사서비스',
 '스포츠/운동',
 '시계/귀금속소매',
 '실내운동시설',
 '실외운동시설',
 '애견/애완/동물',
 '양식',
 '연극/영화/극장',
 '예술품/골동품/수석/분재',
 '예식/의례/관혼상제',
 '요가/단전/마사지',
 '운동/경기용품소매',
 '운송/배달/택배',
 '운영관리시설',
 '유스호스텔',
 '유아교육',
 '유아용품',
 '유흥주점',
 '음/식료품소매',
 '음식배달서비스',
 '의복의류',
 '의약/의료품소매',
 '이/미용/건강',
 '인력/고용/용역알선',
 '일식/수산물',
 '자동차/이륜차',
 '자동차/자동차용품',
 '장례/묘지',
 '전시/관람',
 '제과제빵떡케익',
 '종교용품판매',
 '종합소매점',
 '주유소/충전소',
 '주택수리',
 '중고품소매/교환',
 '중식',
 '책/서적/도서',
 '철물/난방/건설자재소매',
 '취미/오락관련소매',
 '캠프/별장/펜션',
 '커피점/카페',
 '패스트푸드',
 '페인트/유리제품소매',
 '평가/개발/관리',
 '학문교육기타',
 '학원-보습교습입시',
 '학원-어학',
 '학원-예능취미체육',
 '학원-음악미술무용',
 '학원-자격/국가고시',
 '학원-창업취업취미',
 '학원-컴퓨터',
 '학원기타',
 '한식',
 '행사/이벤트',
 '호텔/콘도',
 '화장품소매'}

In [14]:
# 카페만 뽑아내기
df_coffee = data[data["상권업종중분류명"] == "커피점/카페"]

In [15]:
df_coffee

                 상호명   지점명 상권업종대분류명 상권업종중분류명    시도명 시군구명  행정동명
53               커피락   NaN       음식   커피점/카페  광주광역시  광산구  첨단1동
55              카페드맹   NaN       음식   커피점/카페  광주광역시   남구   사직동
61                로다   NaN       음식   커피점/카페  광주광역시   동구  지원2동
140            더치앤더치   NaN       음식   커피점/카페  광주광역시   동구   충장동
215             노니까페   NaN       음식   커피점/카페  광주광역시  광산구   신가동
...              ...   ...      ...      ...    ...  ...   ...
68951             카페   315       음식   커피점/카페  광주광역시   동구   학운동
68953           멜로먼트   NaN       음식   커피점/카페  광주광역시  광산구   하남동
68959      남양공간LED조명   NaN       음식   커피점/카페  광주광역시   북구  운암2동
68963  작은도서관꿈터&북카페넛치   NaN       음식   커피점/카페  광주광역시   서구  화정3동
68970           파운데이  호남대점       음식   커피점/카페  광주광역시  광산구   어룡동

[3086 rows x 7 columns]

In [16]:
df_coffee.index = range(len(df_coffee))

In [18]:
df_coffee

                상호명   지점명 상권업종대분류명 상권업종중분류명    시도명 시군구명  행정동명
0               커피락   NaN       음식   커피점/카페  광주광역시  광산구  첨단1동
1              카페드맹   NaN       음식   커피점/카페  광주광역시   남구   사직동
2                로다   NaN       음식   커피점/카페  광주광역시   동구  지원2동
3             더치앤더치   NaN       음식   커피점/카페  광주광역시   동구   충장동
4              노니까페   NaN       음식   커피점/카페  광주광역시  광산구   신가동
...             ...   ...      ...      ...    ...  ...   ...
3081             카페   315       음식   커피점/카페  광주광역시   동구   학운동
3082           멜로먼트   NaN       음식   커피점/카페  광주광역시  광산구   하남동
3083      남양공간LED조명   NaN       음식   커피점/카페  광주광역시   북구  운암2동
3084  작은도서관꿈터&북카페넛치   NaN       음식   커피점/카페  광주광역시   서구  화정3동
3085           파운데이  호남대점       음식   커피점/카페  광주광역시  광산구   어룡동

[3086 rows x 7 columns]

In [23]:
# 광산구에 위치하고 있는 점포만 뽑아내자.
df_gwangsan_coffee = data[data["시도명"]=="광산구"]

In [24]:
df_gwangsan_coffee.head() # ??????

Empty DataFrame
Columns: [상호명, 지점명, 상권업종대분류명, 상권업종중분류명, 시도명, 시군구명, 행정동명]
Index: []

In [25]:
df_gwangsan_coffee

Empty DataFrame
Columns: [상호명, 지점명, 상권업종대분류명, 상권업종중분류명, 시도명, 시군구명, 행정동명]
Index: []

In [26]:
df_gwangsan_coffee = df_coffee[df_coffee["시도명"]=="광산구"]
df_gwangsan_coffee # ?????????

Empty DataFrame
Columns: [상호명, 지점명, 상권업종대분류명, 상권업종중분류명, 시도명, 시군구명, 행정동명]
Index: []